name: autofix.ci  # needed to securely identify the workflow

on:
  pull_request:
  push:
    branches: [ "main", "develop" ]
permissions:
  contents: read

env:
  rust_toolchain: stable

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.rust_toolchain }}
          components: rustfmt, clippy
      - uses: actions/checkout@v7
      - uses: actions/cache@v6
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/bin/registry/index/
            ~/.cargo/bin/registry/cache/
            ~/.cargo/git/db/
            target/
          key: autofix-${{  hashFiles('**/Cargo.lock') }}

      - run: cargo clippy --fix --workspace
      - run: cargo fmt --all

      - uses: autofix-ci/action@c5b2d67aa2274e7b5a18224e8171550871fc7e4a
